### ISSUE TITLE
Finalize repo QA compliance

### ISSUE THREAD

**Issue by BTT21000** [api3dao/design-tokens#4]
As part of the TM issue https://github.com/api3dao/tasks/issues/849 for QA, some requirements need to be addressed:

### Repo setup requirements as per [new_repo_creation_checklist.md](https://github.com/api3dao/tasks/blob/main/Technical%20management/Tasks%20documentation/new_repo_creation_checklist.md):

- [x] Link the repo to some relevant page if applicable
- [x] Add the relevant license file LICENSE.md consistent with the organisational standards or project requirements.
- [x] Review and confirm the repository’s settings align with the organization’s compliance and security protocols. (e.g. cross check https://github.com/api3dao/design-tokens/security)
- [x] Install Renovate in the repository, following the guidelines outlined in [dependencyManagementStrategy.md](https://github.com/api3dao/tasks/blob/main/Technical%20management/Tasks%20documentation/dependencyManagementStrategy.md).
- [x] Create a renovate.json configuration file in the root of the repository to manage dependencies effectively, as per our dependency management strategy.
- [x] Set up Renovate (or Dependabot or a similar tool) for automated security vulnerability scanning to detect vulnerabilities in the codebase.

**Comment by Anboias** [comment]
AFAICT all steps are completed. It would be great if @BTT21000 or someone else can review them 🙏

**Comment by BTT21000** [comment]
> AFAICT all steps are completed. It would be great if @BTT21000 or someone else can review them 🙏

LGTM! I'm closing the issue. Thank you
